// <auto-generated />
namespace TravelApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m1501 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m1501));
        
        string IMigrationMetadata.Id
        {
            get { return "201901151051166_m1501"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
