// <auto-generated />
namespace TravelApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mg1601 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mg1601));
        
        string IMigrationMetadata.Id
        {
            get { return "201901160520551_mg1601"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
